FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core/ ./core/

RUN mkdir -p checkpoints outputs data_shards

ENV PS_HOST=eq-ps
ENV PS_PORT=50051
ENV WORKER_ID=0

EXPOSE 50052

CMD python core/worker.py --id ${WORKER_ID} --epochs 20